
#define NTYPES 2

typedef enum ENTITY {   NOTHING = 0,  SOMETHING = 222 } Entity;
Entity types[] = {  NOTHING, SOMETHING };
char entity_to_char( Entity e ) { 
switch ( e ) {
    case NOTHING: return '_';

    case SOMETHING: return '@';
 default: return '?'; } }


#define G630_width 3
#define G630_height 3
#define G630_len 9
Entity G630[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G631_width 3
#define G631_height 3
#define G631_len 9
Entity G631[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G641_width 3
#define G641_height 3
#define G641_len 9
Entity G641[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G642_width 3
#define G642_height 3
#define G642_len 9
Entity G642[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G644_width 3
#define G644_height 3
#define G644_len 9
Entity G644[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G645_width 3
#define G645_height 3
#define G645_len 9
Entity G645[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G647_width 3
#define G647_height 3
#define G647_len 9
Entity G647[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G648_width 3
#define G648_height 3
#define G648_len 9
Entity G648[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G650_width 3
#define G650_height 3
#define G650_len 9
Entity G650[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G651_width 3
#define G651_height 3
#define G651_len 9
Entity G651[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G653_width 3
#define G653_height 3
#define G653_len 9
Entity G653[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G654_width 3
#define G654_height 3
#define G654_len 9
Entity G654[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G656_width 3
#define G656_height 3
#define G656_len 9
Entity G656[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G657_width 3
#define G657_height 3
#define G657_len 9
Entity G657[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G659_width 3
#define G659_height 3
#define G659_len 9
Entity G659[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G660_width 3
#define G660_height 3
#define G660_len 9
Entity G660[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G662_width 3
#define G662_height 3
#define G662_len 9
Entity G662[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G663_width 3
#define G663_height 3
#define G663_len 9
Entity G663[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G665_width 3
#define G665_height 3
#define G665_len 9
Entity G665[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G666_width 3
#define G666_height 3
#define G666_len 9
Entity G666[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G668_width 3
#define G668_height 3
#define G668_len 9
Entity G668[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G669_width 3
#define G669_height 3
#define G669_len 9
Entity G669[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G671_width 3
#define G671_height 3
#define G671_len 9
Entity G671[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G672_width 3
#define G672_height 3
#define G672_len 9
Entity G672[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G674_width 3
#define G674_height 3
#define G674_len 9
Entity G674[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G675_width 3
#define G675_height 3
#define G675_len 9
Entity G675[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G677_width 3
#define G677_height 3
#define G677_len 9
Entity G677[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G678_width 3
#define G678_height 3
#define G678_len 9
Entity G678[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G680_width 3
#define G680_height 3
#define G680_len 9
Entity G680[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G681_width 3
#define G681_height 3
#define G681_len 9
Entity G681[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G683_width 3
#define G683_height 3
#define G683_len 9
Entity G683[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G684_width 3
#define G684_height 3
#define G684_len 9
Entity G684[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G686_width 3
#define G686_height 3
#define G686_len 9
Entity G686[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G687_width 3
#define G687_height 3
#define G687_len 9
Entity G687[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G689_width 3
#define G689_height 3
#define G689_len 9
Entity G689[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G690_width 3
#define G690_height 3
#define G690_len 9
Entity G690[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G692_width 3
#define G692_height 3
#define G692_len 9
Entity G692[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G693_width 3
#define G693_height 3
#define G693_len 9
Entity G693[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G695_width 3
#define G695_height 3
#define G695_len 9
Entity G695[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G696_width 3
#define G696_height 3
#define G696_len 9
Entity G696[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G698_width 3
#define G698_height 3
#define G698_len 9
Entity G698[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G699_width 3
#define G699_height 3
#define G699_len 9
Entity G699[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G701_width 3
#define G701_height 3
#define G701_len 9
Entity G701[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G702_width 3
#define G702_height 3
#define G702_len 9
Entity G702[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G704_width 3
#define G704_height 3
#define G704_len 9
Entity G704[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G705_width 3
#define G705_height 3
#define G705_len 9
Entity G705[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G707_width 3
#define G707_height 3
#define G707_len 9
Entity G707[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G708_width 3
#define G708_height 3
#define G708_len 9
Entity G708[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G710_width 3
#define G710_height 3
#define G710_len 9
Entity G710[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G711_width 3
#define G711_height 3
#define G711_len 9
Entity G711[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G713_width 3
#define G713_height 3
#define G713_len 9
Entity G713[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G714_width 3
#define G714_height 3
#define G714_len 9
Entity G714[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G716_width 3
#define G716_height 3
#define G716_len 9
Entity G716[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G717_width 3
#define G717_height 3
#define G717_len 9
Entity G717[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G719_width 3
#define G719_height 3
#define G719_len 9
Entity G719[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G720_width 3
#define G720_height 3
#define G720_len 9
Entity G720[] = {  NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING, NOTHING, SOMETHING, NOTHING };


#define G722_width 3
#define G722_height 3
#define G722_len 9
Entity G722[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G723_width 3
#define G723_height 3
#define G723_len 9
Entity G723[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G725_width 3
#define G725_height 3
#define G725_len 9
Entity G725[] = {  NOTHING, NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G726_width 3
#define G726_height 3
#define G726_len 9
Entity G726[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G728_width 3
#define G728_height 3
#define G728_len 9
Entity G728[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G729_width 3
#define G729_height 3
#define G729_len 9
Entity G729[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };


#define G731_width 3
#define G731_height 3
#define G731_len 9
Entity G731[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING, NOTHING };


#define G732_width 3
#define G732_height 3
#define G732_len 9
Entity G732[] = {  NOTHING, NOTHING, NOTHING, SOMETHING, SOMETHING, SOMETHING, NOTHING, NOTHING, NOTHING };

#define match_patterns_len 32
Entity * match_patterns[] = {  G630, G641, G644, G647, G650, G653, G656, G659, G662, G665, G668, G671, G674, G677, G680, G683, G686, G689, G692, G695, G698, G701, G704, G707, G710, G713, G716, G719, G722, G725, G728, G731 };

#define match_patterns_len 32
Entity * replace_patterns[] = {  G631, G642, G645, G648, G651, G654, G657, G660, G663, G666, G669, G672, G675, G678, G681, G684, G687, G690, G693, G696, G699, G702, G705, G708, G711, G714, G717, G720, G723, G726, G729, G732 };
